from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, RadioField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import User

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

class RoleAssignForm(FlaskForm):
    username = StringField('Type your username', validators=[DataRequired()])
    is_student = BooleanField('I am a Student')
    is_teacher = BooleanField('I am a Teacher')
    is_admin = BooleanField('I am an Administrator')
    teacher_valid = PasswordField('     Enter Teacher Code')
    admin_valid = PasswordField('       Enter Admin Code')
    submit = SubmitField('Proceed')

class LEPickerForm(FlaskForm):
    s1k1 = BooleanField('The central purpose of scientific inquiry is to develop explanations of natural phenomena in a continuing and creative process')
    s1k2 = BooleanField('Beyond the use of reasoning and consensus, scientific inquiry involves the testing of proposed explanations involving the use of conventional techniques and procedures and usually requiring considerable ingenuity')
    s1k3 = BooleanField('The observations made while testing proposed explanations, when analyzed using conventional and invented methods, provide new insights into natural phenomena')
    s4k1 = BooleanField('Living things are both similar and different from each other and from nonliving things')
    s4k2 = BooleanField('Organisms inherit genetic information in a variety of ways that result in continuity of structure and function between parents and offspring')
    s4k3 = BooleanField('Individual organisms and species change over time')
    s4k4 = BooleanField('The continuity of life is sustatined through reproduction and development')
    s4k5 = BooleanField('Organisms maintain a dynamic equilibrium that sustains life')
    s4k6 = BooleanField('Plants and animals depend on each other and their physical environment')
    s4k7 = BooleanField('Human decisions and activities have had a profound impact on the physical and living environment')
    l1 = BooleanField('Relationships and Biodiversity')
    l2 = BooleanField('Making Connections')
    l3 = BooleanField('Beaks of Finches')
    l5 = BooleanField('Diffusion Through A Membrane')
    search_submit = SubmitField('Show Results')

class StudentAssessmentForm(FlaskForm):
    responses1 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation1 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses2 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation2 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses3 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation3 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses4 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation4 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses4 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation4 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses5 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation5 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses6 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation6 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses7 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation7 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses8 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation8 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses9 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation9 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses10 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation10 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses11 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation11 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses12 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation12 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses13 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation13 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses14 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation14 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses15 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation15 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses16 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation16 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses17 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation17 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses18 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation18 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses19 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation19 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses20 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation20 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses21 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation21 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses22 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation22 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses23 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation23 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses24 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation24 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    responses25 = RadioField('Answer', choices=[('1','1'),('2','2'), ('3','3'), ('4','4')])
    explanation25 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    final_submit = SubmitField('Submit')

class GradeAssessmentForm(FlaskForm):
    feedback1 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback2 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback3 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback4 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback5 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback6 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback7 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback8 = TextAreaField('', render_kw={"rows": 5, "cols": 100})
    feedback9 = TextAreaField('', render_kw={"rows": 5, "cols": 100})
    feedback10 = TextAreaField('', render_kw={"rows": 5, "cols": 100})
    final_submit = SubmitField('Submit')

class TeacherClassForm(FlaskForm):
    grades_submit = SubmitField('Grades')
    people_submit = SubmitField('People')
    create_submit = SubmitField('Create Assignment')
    classes_submit = SubmitField('Back to Classes')

class AssignmentOptionsForm(FlaskForm):
    assignment_name = StringField('Assignment Name', validators=[DataRequired()])
    display_score = BooleanField('Display student score on submit')
    display_comments = BooleanField('Display feedback on submit')
    multiple_attempts = BooleanField('Allow multiple attempts')
    pdf_disable = BooleanField('Disable PDF generation')
    pdf_copy_spanish = BooleanField('Spanish')
    pdf_copy_chinese = BooleanField('Chinese')
    pdf_copy_creole = BooleanField('Haitian Creole')
    pdf_copy_korean = BooleanField('Korean')
    pdf_copy_russian = BooleanField('Russian')
    custom_submit = SubmitField('Create Assignment')
    feedback1 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback2 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback3 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback4 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback5 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback6 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback7 = TextAreaField('', render_kw={"rows": 10, "cols": 50})
    feedback8 = TextAreaField('', render_kw={"rows": 5, "cols": 100})
    feedback9 = TextAreaField('', render_kw={"rows": 5, "cols": 100})
    feedback10 = TextAreaField('', render_kw={"rows": 5, "cols": 100})
